#basepageref = 'https://tuttu.github.io/StellarisAssets/'
defaultContentLanguage = 'en'
title = 'Stellaris Assets'
theme = "StellarisTheme"
#sectionPagesMenu = 'main'

[languages]
  [languages.en]
    disabled = false
    baseURL = 'https://tuttu.github.io/StellarisAssets/'
    languageCode = 'en'
    languageDirection = 'ltr'
    weight = 0
  [languages.fr]
    disabled = false
    baseURL = 'https://tuttu.github.io/StellarisAssets/MEM'
    languageCode = 'fr'
    languageDirection = 'ltr'
    weight = 1