[[menu.main]]
    identifier = "civics"
    name = 'Civics'
    pageref = '/civics'
    weight = 1
[[menu.main]]
    identifier = "crisis"
    name = 'Crisis'
    pageref = '/crisis'
    weight = 1
[[menu.main]]
    identifier = "events"
    name = "Events"
    weight = 1
[[menu.main]]
    identifier = "event_pictures"
    name = 'Pictures'
    pageref = '/event_pictures'
    parent = "events"
    weight = 1
[[menu.main]]
    identifier = "event_sounds"
    name = 'Sounds'
    pageref = '/sounds'
    parent = "events"
    weight = 1
[[menu.main]]
    identifier = "origins"
    name = "Origins"
    weight = 1
[[menu.main]]
    identifier = "origin_icons"
    name = 'Icons'
    pageref = '/origin_icons'
    parent = "origins"
    weight = 1
[[menu.main]]
    identifier = "origin_pictures"
    name = 'Pictures'
    pageref = '/origin_pictures'
    parent = "origins"
    weight = 1
[[menu.main]]
    identifier = "planets"
    name = "Planets"
    weight = 1
[[menu.main]]
    identifier = "planet_buildings"
    name = 'Buildings'
    pageref = '/buildings'
    parent = "planets"
    weight = 1
[[menu.main]]
    identifier = "planet_decisions"
    name = 'Decisions'
    pageref = '/decisions'
    parent = "planets"
    weight = 1
[[menu.main]]
    identifier = "planet_deposits"
    name = 'Deposits'
    pageref = '/deposits'
    parent = "planets"
    weight = 1
[[menu.main]]
    identifier = "planet_jobs"
    name = 'Jobs'
    pageref = '/jobs'
    parent = "planets"
    weight = 1
[[menu.main]]
    identifier = "planet_modifiers"
    name = 'Modifiers'
    pageref = '/planet_modifiers'
    parent = "planets"
    weight = 1
[[menu.main]]
    identifier = "modifiers"
    name = 'Modifiers'
    pageref = '/modifiers'
    weight = 1
[[menu.main]]
    identifier = "modules"
    name = 'Modules'
    pageref = '/modules'
    weight = 1
[[menu.main]]
    identifier = "mutations"
    name = 'Mutations'
    pageref = '/mutations'
    weight = 1
[[menu.main]]
    identifier = "relics"
    name = 'Relics'
    pageref = '/relics'
    weight = 1
[[menu.main]]
    identifier = "rooms"
    name = 'Rooms'
    pageref = '/rooms'
    weight = 1
[[menu.main]]
    identifier = "runes"
    name = 'Runes'
    pageref = '/runes'
    weight = 1
[[menu.main]]
    identifier = "ship_parts"
    name = "Ship Parts"
    pageref = '/ship_parts'
    weight = 1
[[menu.main]]
    identifier = "situations"
    name = "Situations"
    pageref = '/situations'
    weight = 1
[[menu.main]]
    identifier = "situation_icons"
    name = 'Icons'
    pageref = '/situation_icons'
    parent = "situations"
    weight = 1
[[menu.main]]
    identifier = "situation_logs"
    name = 'Logs'
    pageref = '/situation_log'
    parent = "situations"
    weight = 1
[[menu.main]]
    identifier = "specimens"
    name = 'Specimens'
    pageref = '/specimens'
    weight = 1
[[menu.main]]
    identifier = "traits"
    name = 'Traits'
    pageref = '/traits'
    weight = 1
[[menu.main]]
    identifier = "messages"
    name = 'Messages'
    pageref = '/messages'
    weight = 1