baseURL = 'https://tuttu.github.io/StellarisAssets/'
languageCode = 'en-us'
title = 'Stellaris Assets'
theme = "StellarisTheme"
#sectionPagesMenu = 'main'

[menu]
[[menu.main]]
    name = 'Buildings'
    pageRef = '/buildings'
    weight = 10
[[menu.main]]
    name = 'Decisions'
    pageRef = '/decisions'
    weight = 10
[[menu.main]]
    name = 'Deposits'
    pageRef = '/deposits'
    weight = 10
[[menu.main]]
    name = 'Event Pictures'
    pageRef = '/event_pictures'
    weight = 10
[[menu.main]]
    name = 'Jobs'
    pageRef = '/jobs'
    weight = 10
[[menu.main]]
    name = 'Modifiers'
    pageRef = '/modifiers'
    weight = 10
[[menu.main]]
    name = 'Modules'
    pageRef = '/modules'
    weight = 10
[[menu.main]]
    name = 'Origin Icons'
    pageRef = '/origin_icons'
    weight = 10
[[menu.main]]
    name = 'Origin Pictures'
    pageRef = '/origin_pictures'
    weight = 10
[[menu.main]]
    name = 'Planet Modifiers'
    pageRef = '/planet_modifiers'
    weight = 10
[[menu.main]]
    name = 'Relics'
    pageRef = '/relics'
    weight = 10
[[menu.main]]
    name = 'Rooms'
    pageRef = '/rooms'
    weight = 10
[[menu.main]]
    name = 'Runes'
    pageRef = '/runes'
    weight = 10
[[menu.main]]
    name = 'Situation Icons'
    pageRef = '/situation_icons'
    weight = 10
[[menu.main]]
    name = 'Situation Log'
    pageRef = '/situation_log'
    weight = 10
[[menu.main]]
    name = 'Sounds'
    pageRef = '/sounds'
    weight = 10
[[menu.main]]
    name = 'Traits'
    pageRef = '/traits'
    weight = 10